[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/carlo-rondon.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.docx"
  [headers.values]
    Content-Disposition = "attachment"
